### ISSUE TITLE
does f411 use the same footprint?

### ISSUE THREAD

**Issue by bathoorn** [ibnuda/simpleton#2]
there is a f411 based blackpill too, do you know if that uses the same footprint?

**Comment by ibnuda** [comment]
https://raw.githubusercontent.com/WeActTC/MiniF4-STM32F4x1/master/HDK/MiniF4x1Cx_V20%20Board%20Shape%20%E5%A4%96%E5%BD%A2.pdf

**Comment by bathoorn** [comment]
thanx, indeed the same.
